project:
  type: website
  render:
    - index.qmd
    - Courses/Bash/tp.qmd
    - Courses/CI/tp.qmd
    - Courses/Docs/tp.qmd
    - Courses/Git/tp.qmd
    - Courses/IDE/tp.qmd
    - Courses/Pandas/tp.qmd
    - Courses/Python-modules/tp.qmd
    - Courses/ScipyNumpy/tp.qmd
    - Courses/Numpy/tp.qmd
    - Courses/Test/tp.qmd
    - Courses/TimeMemory/tp.qmd
    - Courses/Venv/tp.qmd
    - Courses/ClassesExceptions/tp.qmd
    - Projects/README.qmd
    - Projects/2021-2022/README.qmd
    - Projects/2022-2023/README.qmd
    - Projects/2023-2024/README.qmd
    - Projects/README.qmd

website:
  title: "HAX815X: Software development for data sciences"
  site-url: https://bcharlier.github.io/HAX815X/
  repo-url: https://github.com/bcharlier/HAX815X
  page-navigation: true
  repo-actions: [source, issue]
  navbar:
    title: HAX815X
    background: primary
    search: true
    left:
      - text: "Overview"
        href: index.qmd
      - text: "Courses"
        menu:
          - Courses/Bash/tp.qmd
          - Courses/Git/tp.qmd
          - Courses/IDE/tp.qmd
          - Courses/Venv/tp.qmd
          - Courses/CI/tp.qmd
          - Courses/Docs/tp.qmd
          - text: "---"
          - Courses/Python-modules/tp.qmd
          - Courses/ClassesExceptions/tp.qmd
          - Courses/Test/tp.qmd
          - Courses/Pandas/tp.qmd
          - Courses/Numpy/tp.qmd
          - Courses/ScipyNumpy/tp.qmd
          - Courses/TimeMemory/tp.qmd
      - text: "Projects"
        menu:
          - text: "Guidelines"
            href: Projects/README.qmd
          - text: "2023-2024"
            href: Projects/2023-2024/README.qmd
      - text: "Bonus"
        href: Bonus/README.qmd
    tools:
      - icon: github
        href: https://github.com/bcharlier/HAX815X
        text: GitHub
      - icon: bicycle
        href: https://moodle.umontpellier.fr/course/view.php?id=24820
        text: Moodle

format:
  html:
    theme: flatly
    css: custom.scss
    # mainfont: Atkinson Hyperlegible
    html-math-method: katex
    toc-location: right
    toc: true
    toc-depth: 3
    code-fold: false
    code-tools:
      toggle: false
      source: false
    code-overflow: wrap
    highlight-style: github
    fig-responsive: true
    fig.align: center
    # self-contained: true
    # fig-format: svg
