project:
  type: website
  render:
    - index.qmd
    - Courses/Bash/tp.qmd
    - Courses/CI/tp.qmd
    - Courses/Docs/tp.qmd
    - Courses/Git/tp.qmd
    - Courses/IDE/tp.qmd
    - Courses/Pandas/pandas_titanic.qmd
    - Courses/Pandas/pandas_airparif.qmd
    - Courses/Pandas/pandas_bikes.qmd
    - Courses/Python-modules/tp.qmd
    - Courses/ScipyNumpy/tp.qmd
    - Courses/Numpy/tp.qmd
    - Courses/Test/tp.qmd
    - Courses/TimeMemory/tp.qmd
    - Courses/Venv/tp.qmd
    - Courses/ClassesExceptions/tp.qmd
    - Courses/Visualization/tp.qmd
    - Projects/2023-2024/README.qmd

website:
  back-to-top-navigation: true
  page-navigation: true # true not working in website
  title: "HAB796B9: Software development for data sciences"
  site-url: https://bcharlier.github.io/HAB796B9/
  repo-url: https://github.com/bcharlier/HAB796B9
  repo-actions: [source, issue]
  # sidebar:
  # left:
  #   contents:
  #     - section: "Overview"
  #       contents:
  #         - href: index.qmd
  #     - section: "Courses"
  # contents:
  #   - href: Courses/Bash/tp.qmd
  #   - href: Courses/Git/tp.qmd
  #   - href: Courses/IDE/tp.qmd
  #   - href: Courses/Venv/tp.qmd
  #   - href: Courses/CI/tp.qmd
  #   - href: Courses/Docs/tp.qmd
  #   - href: Courses/Python-modules/tp.qmd
  #   - href: Courses/ClassesExceptions/tp.qmd
  #   - href: Courses/Test/tp.qmd
  #   - href: Courses/Pandas/tp.qmd
  #   - href: Courses/Numpy/tp.qmd
  #   - href: Courses/ScipyNumpy/tp.qmd
  #   - href: Courses/TimeMemory/tp.qmd
  # menu: false
  navbar:
    title: HAB796B9
    background: primary
    search: true
    tools:
      - icon: bicycle
        href: https://moodle.umontpellier.fr/course/view.php?id=24820
        text: Moodle
      - icon: github
        href: https://github.com/bcharlier/HAB796B9
        text: GitHub
    left:
      # - text: "Overview"
      #   href: index.qmd
      - sidebar:general
      - sidebar:python
      - sidebar:grading
  sidebar:
    - id: general
      title: "General tools"
      collapse-level: 3
      contents:
        - Courses/Bash/tp.qmd
        - Courses/Git/tp.qmd
        - Courses/IDE/tp.qmd
        - Courses/CI/tp.qmd
        - Courses/Docs/tp.qmd
    - id: python
      title: "Python"
      collapse-level: 3
      contents:
        - section: "Dev. Tools"
          contents:
            - Courses/Venv/tp.qmd
            - Courses/ClassesExceptions/tp.qmd
            - Courses/Python-modules/tp.qmd
            - Courses/Test/tp.qmd
        - section: "Scientific Python"
          contents:
            - Courses/Numpy/tp.qmd
            - Courses/ScipyNumpy/tp.qmd
            - Courses/TimeMemory/tp.qmd
            - Courses/Visualization/tp.qmd
        - section: "Pandas"
          contents:
            - Courses/Pandas/pandas_titanic.qmd
            - Courses/Pandas/pandas_airparif.qmd
            - Courses/Pandas/pandas_bikes.qmd
    - id: grading
      title: "Grading"
      collapse-level: 2
      contents:
         - Projects/2023-2024/README.qmd

format:
  html:
    theme: lux
    # mainfont: Atkinson Hyperlegible
    html-math-method: katex
    number-sections: false
    toc-depth: 3
    code-fold: false
    code-tools:
      toggle: false
      source: false
    code-overflow: wrap
    highlight-style: github
    fig-responsive: true
    fig.align: center
    reference-location: margin
    citation-location: margin
    # self-contained: true
    # fig-format: svg
    css: custom.scss
